### PR TITLE
Try building in GCC 4.8 and 6

### PR DESCRIPTION
**Pull request by curiousdannii**
I'm not sure if this will work, lets see what Travis does...

### CODE REVIEW

**Comment by curiousdannii** [comment]
I guess the build matrix works because the new scottfree failed only in 4.8!

**Comment by cspiegel** [comment]
The timing really couldn't be better... I just pushed that Scott change half an hour ago.  I'll update the Jamfile to specify C99 mode for it, which should get it working with 4.8.

**Comment by cspiegel** [comment]
OK, C99 has been enabled.  With luck merging master should cause the next build to succeed.

**Comment by cspiegel** [comment]
With the scott C99 fix, both 4.8 and 6 now pass. Thanks for doing this!

**Pull request merged**
