### PR TITLE
Add CMake support

### PR DESCRIPTION
**Pull request by cspiegel**

### CODE REVIEW

**Comment by curiousdannii** [comment]
Can you build garglk as a static library with these Cmake definitions?

**Comment by cspiegel** [comment]
> Can you build garglk as a static library with these Cmake definitions?

Not currently, but that's a great suggestion.  I'll add support for static library.

**Comment by cspiegel** [comment]
OK, `-DBUILD_SHARED_LIBS=OFF` will now build a static `libgarglk`.

**Comment by curiousdannii** [comment]
Fantastic! Thanks :)

**Comment by curiousdannii** [comment]
While I'm here dropping wishes, how difficult would it be to add a setting to only build the garglk library? Or is that not even necessary, if we just build the garglk/ folder directly rather than the toplevel CMakeLists.txt?

**Comment by cspiegel** [comment]
@curiousdannii I've just added two flags: `WITH_INTERPRETERS` and `WITH_LAUNCHER`.  If those are set to false, then only the library will be built.

**Pull request merged**
