### PR TITLE
typos

### PR DESCRIPTION
**Pull request by a-detiste**

### CODE REVIEW

**Comment by salty-horse** [comment]
Typos in interpreters should be reported upstream.

**Comment by a-detiste** [comment]
yup

**Comment by salty-horse** [comment]
Sorry, was it clear enough? I apologize if it came off as rude.

Each of the files with typos actually belong to different projects. Garglk just bundled the released versions.

**Comment by a-detiste** [comment]
no it wan't rude at all :smile:; I think I was myself rude by not acknoweledging this sooner

**Pull request closed without merging**
