### PR TITLE
Hugo: Update to 3.3.0

### PR DESCRIPTION
**Pull request by curiousdannii**
Fix FileIO() errors (#248)

I didn't realise there would be so many line ending changes. I'm not really sure how to fix that sorry.

And I'm also sorry that I haven't tested it with Gargoyle's build system. (No, I'm not the best contributor.)

### CODE REVIEW

**Comment by salty-horse** [comment]
Perhaps the line-ending changes (changed from dos-style to unix-style) can be done in a separate commit, one that will show no changes when running `git diff --ignore-space-change`.
I can split those up if you wish.

Your commit is missing a space in `terps/status.txt`. While we're at it, it can be changed to unix newlines.

**Comment by curiousdannii** [comment]
That sounds like a great plan @salty-horse. If you could split it up for me that would be awesome!

**Comment by salty-horse** [comment]
You can find my changes here:

https://github.com/garglk/garglk/compare/master...salty-horse:hugo_stuff?expand=1

I took the liberty of adding the missing space in your change to terps/status.txt, and I added a newline to your commit, so it would show up better in git (which likes the first line to be a summary, and any detailed description appearing two lines below it)

**Comment by cspiegel** [comment]
@salty-horse, do you want to make a PR based on your changes?

Also, quick note, it looks like the old version of hugo is still listed in terps/status.txt.

**Comment by salty-horse** [comment]
@cspiegel fixed, and opened #255

**Pull request closed without merging**
